# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wupadupa
email: wupadupa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wupadupa - a collective of musicians who put on evenings of quality entertainment with the best music, visuals, comfy cusions and free cake around.
baseurl: "" # the subpath of your site, e.g. /blog
url: "//www.wupadupa.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wupadupa
# github_username:  jekyll

sass:
    style: compressed

doodlebook-base: /doodlebook
doodlebook-images-base: "/images/doodlebook/"
doodlebook-total: 135

# collections_dir: my_collections
collections:
  doodlebook:
    output: true  
    # permalink: /doodlebook/:collection/:name
    # layout: doodlebook
    
defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: "doodlebook"



# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
